package com.kamilbeben.zombiestorm.tools;

import com.badlogic.gdx.graphics.Texture;

/**
 * Created by bezik on 12.10.16.
 */
public class TextureHolder {

    public Texture HUD_AMMO_BACKGROUND;

    public Texture HUD_AMMO_ON;
    public Texture HUD_AMMO_OFF;

    public Texture GAME_EXTRAS_AMMOPACK;
    public Texture GAME_EXTRAS_GRASS_ANIMATION;
    public Texture GAME_EXTRAS_FIREFLY_GREEN;
    public Texture GAME_EXTRAS_FIREFLY_BLUE;;
    public Texture GAME_EXTRAS_FIREFLY_TRANSPARENT;
    public Texture GAME_EXTRAS_PALETTE;
    public Texture GAME_EXTRAS_BACKGROUND;
    public Texture GAME_EXTRAS_PARALLAX_MOUNTAINS_FAR;
    public Texture GAME_EXTRAS_PARALLAX_MOUNTAINS_CLOSE;
    public Texture GAME_EXTRAS_PARALLAX_FOG;

    public Texture GAME_ENEMY_CAR;
    public Texture GAME_ENEMY_MONKEY;
    public Texture GAME_ENEMY_WALKER;
    public Texture GAME_PLAYER;
    public Texture GAME_PLAYER_EXTENDED;

    public Texture GAME_OBSTACLE_HOLE_LONG;
    public Texture GAME_OBSTACLE_HOLE_SHORT;
    public Texture GAME_OBSTACLE_ISLAND_LONG;
    public Texture GAME_OBSTACLE_ISLAND_SHORT;


    public TextureHolder(Texture HUD_AMMO_BACKGROUND, Texture HUD_AMMO_ON, Texture HUD_AMMO_OFF, Texture GAME_EXTRAS_AMMOPACK, Texture GAME_EXTRAS_GRASS_ANIMATION, Texture GAME_EXTRAS_FIREFLY_GREEN, Texture GAME_EXTRAS_FIREFLY_BLUE, Texture GAME_EXTRAS_FIREFLY_TRANSPARENT, Texture GAME_EXTRAS_PALETTE, Texture GAME_EXTRAS_BACKGROUND, Texture GAME_EXTRAS_PARALLAX_MOUNTAINS_FAR, Texture GAME_EXTRAS_PARALLAX_MOUNTAINS_CLOSE, Texture GAME_EXTRAS_PARALLAX_FOG, Texture GAME_ENEMY_CAR, Texture GAME_ENEMY_MONKEY, Texture GAME_ENEMY_WALKER, Texture GAME_PLAYER, Texture GAME_PLAYER_EXTENDED, Texture GAME_OBSTACLE_HOLE_LONG, Texture GAME_OBSTACLE_HOLE_SHORT, Texture GAME_OBSTACLE_ISLAND_LONG, Texture GAME_OBSTACLE_ISLAND_SHORT) {
        this.HUD_AMMO_BACKGROUND = HUD_AMMO_BACKGROUND;
        this.HUD_AMMO_ON = HUD_AMMO_ON;
        this.HUD_AMMO_OFF = HUD_AMMO_OFF;
        this.GAME_EXTRAS_AMMOPACK = GAME_EXTRAS_AMMOPACK;
        this.GAME_EXTRAS_GRASS_ANIMATION = GAME_EXTRAS_GRASS_ANIMATION;
        this.GAME_EXTRAS_FIREFLY_GREEN = GAME_EXTRAS_FIREFLY_GREEN;
        this.GAME_EXTRAS_FIREFLY_BLUE = GAME_EXTRAS_FIREFLY_BLUE;
        this.GAME_EXTRAS_FIREFLY_TRANSPARENT = GAME_EXTRAS_FIREFLY_TRANSPARENT;
        this.GAME_EXTRAS_PALETTE = GAME_EXTRAS_PALETTE;
        this.GAME_EXTRAS_BACKGROUND = GAME_EXTRAS_BACKGROUND;
        this.GAME_EXTRAS_PARALLAX_MOUNTAINS_FAR = GAME_EXTRAS_PARALLAX_MOUNTAINS_FAR;
        this.GAME_EXTRAS_PARALLAX_MOUNTAINS_CLOSE = GAME_EXTRAS_PARALLAX_MOUNTAINS_CLOSE;
        this.GAME_EXTRAS_PARALLAX_FOG = GAME_EXTRAS_PARALLAX_FOG;
        this.GAME_ENEMY_CAR = GAME_ENEMY_CAR;
        this.GAME_ENEMY_MONKEY = GAME_ENEMY_MONKEY;
        this.GAME_ENEMY_WALKER = GAME_ENEMY_WALKER;
        this.GAME_PLAYER = GAME_PLAYER;
        this.GAME_PLAYER_EXTENDED = GAME_PLAYER_EXTENDED;
        this.GAME_OBSTACLE_HOLE_LONG = GAME_OBSTACLE_HOLE_LONG;
        this.GAME_OBSTACLE_HOLE_SHORT = GAME_OBSTACLE_HOLE_SHORT;
        this.GAME_OBSTACLE_ISLAND_LONG = GAME_OBSTACLE_ISLAND_LONG;
        this.GAME_OBSTACLE_ISLAND_SHORT = GAME_OBSTACLE_ISLAND_SHORT;
    }

}
